version: '3.9'

services:
  db:
    image: postgres:14.3-alpine3.15
    ports:
      - "5431:5432"
    environment:
      POSTGRES_USER: andrey
      POSTGRES_PASSWORD: 990414
      POSTGRES_DB: netology